const_value = 0

	const KT_NOT_KILLABLE                 ; 00
	const KT_CERULEAN_CITY_ROCKET_THIEF   ; 01
	const KT_ROUTE_3_TRAINER_0            ; 02
	const KT_ROUTE_3_TRAINER_1            ; 03
	const KT_ROUTE_3_TRAINER_2            ; 04
	const KT_ROUTE_3_TRAINER_3            ; 05
	const KT_ROUTE_3_TRAINER_4            ; 06
	const KT_ROUTE_3_TRAINER_5            ; 07
	const KT_ROUTE_3_TRAINER_6            ; 08
	const KT_ROUTE_3_TRAINER_7            ; 09
	const KT_ROUTE_4_TRAINER_0            ; 0A
	const KT_ROUTE_6_TRAINER_0            ; 0B
	const KT_ROUTE_6_TRAINER_1            ; 0C
	const KT_ROUTE_6_TRAINER_2            ; 0D
	const KT_ROUTE_6_TRAINER_3            ; 0E
	const KT_ROUTE_6_TRAINER_4            ; 0F
	const KT_ROUTE_6_TRAINER_5            ; 10
	const KT_ROUTE_8_TRAINER_0            ; 11
	const KT_ROUTE_8_TRAINER_1            ; 12
	const KT_ROUTE_8_TRAINER_2            ; 13
	const KT_ROUTE_8_TRAINER_3            ; 14
	const KT_ROUTE_8_TRAINER_4            ; 15
	const KT_ROUTE_8_TRAINER_5            ; 16
	const KT_ROUTE_8_TRAINER_6            ; 17
	const KT_ROUTE_8_TRAINER_7            ; 18
	const KT_ROUTE_8_TRAINER_8            ; 19
	const KT_ROUTE_9_TRAINER_0            ; 1A
	const KT_ROUTE_9_TRAINER_1            ; 1B
	const KT_ROUTE_9_TRAINER_2            ; 1C
	const KT_ROUTE_9_TRAINER_3            ; 1D
	const KT_ROUTE_9_TRAINER_4            ; 1E
	const KT_ROUTE_9_TRAINER_5            ; 1F
	const KT_ROUTE_9_TRAINER_6            ; 20
	const KT_ROUTE_9_TRAINER_7            ; 21
	const KT_ROUTE_9_TRAINER_8            ; 22
	const KT_ROUTE_10_TRAINER_0           ; 23
	const KT_ROUTE_10_TRAINER_1           ; 24
	const KT_ROUTE_10_TRAINER_2           ; 25
	const KT_ROUTE_10_TRAINER_3           ; 26
	const KT_ROUTE_10_TRAINER_4           ; 27
	const KT_ROUTE_10_TRAINER_5           ; 28
	const KT_ROUTE_11_TRAINER_0           ; 29
	const KT_ROUTE_11_TRAINER_1           ; 2A
	const KT_ROUTE_11_TRAINER_2           ; 2B
	const KT_ROUTE_11_TRAINER_3           ; 2C
	const KT_ROUTE_11_TRAINER_4           ; 2D
	const KT_ROUTE_11_TRAINER_5           ; 2E
	const KT_ROUTE_11_TRAINER_6           ; 2F
	const KT_ROUTE_11_TRAINER_7           ; 30
	const KT_ROUTE_11_TRAINER_8           ; 31
	const KT_ROUTE_11_TRAINER_9           ; 32
	const KT_ROUTE_12_TRAINER_0           ; 33
	const KT_ROUTE_12_TRAINER_1           ; 34
	const KT_ROUTE_12_TRAINER_2           ; 35
	const KT_ROUTE_12_TRAINER_3           ; 36
	const KT_ROUTE_12_TRAINER_4           ; 37
	const KT_ROUTE_12_TRAINER_5           ; 38
	const KT_ROUTE_12_TRAINER_6           ; 39
	const KT_ROUTE_16_TRAINER_0           ; 3A
	const KT_ROUTE_16_TRAINER_1           ; 3B
	const KT_ROUTE_16_TRAINER_2           ; 3C
	const KT_ROUTE_16_TRAINER_3           ; 3D
	const KT_ROUTE_16_TRAINER_4           ; 3E
	const KT_ROUTE_16_TRAINER_5           ; 3F
	const KT_ROUTE_17_TRAINER_0           ; 40
	const KT_ROUTE_17_TRAINER_1           ; 41
	const KT_ROUTE_17_TRAINER_2           ; 42
	const KT_ROUTE_17_TRAINER_3           ; 43
	const KT_ROUTE_17_TRAINER_4           ; 44
	const KT_ROUTE_17_TRAINER_5           ; 45
	const KT_ROUTE_17_TRAINER_6           ; 46
	const KT_ROUTE_17_TRAINER_7           ; 47
	const KT_ROUTE_17_TRAINER_8           ; 48
	const KT_ROUTE_17_TRAINER_9           ; 49
	const KT_ROUTE_18_TRAINER_0           ; 4A
	const KT_ROUTE_18_TRAINER_1           ; 4B
	const KT_ROUTE_18_TRAINER_2           ; 4C
	const KT_ROUTE_24_ROCKET              ; 4D
	const KT_ROUTE_24_TRAINER_0           ; 4E
	const KT_ROUTE_24_TRAINER_1           ; 4F
	const KT_ROUTE_24_TRAINER_2           ; 50
	const KT_ROUTE_24_TRAINER_3           ; 51
	const KT_ROUTE_24_TRAINER_4           ; 52
	const KT_ROUTE_24_TRAINER_5           ; 53
	const KT_ROUTE_25_TRAINER_0           ; 54
	const KT_ROUTE_25_TRAINER_1           ; 55
	const KT_ROUTE_25_TRAINER_2           ; 56
	const KT_ROUTE_25_TRAINER_3           ; 57
	const KT_ROUTE_25_TRAINER_4           ; 58
	const KT_ROUTE_25_TRAINER_5           ; 59
	const KT_ROUTE_25_TRAINER_6           ; 5A
	const KT_ROUTE_25_TRAINER_7           ; 5B
	const KT_ROUTE_25_TRAINER_8           ; 5C
	const KT_VIRIDIAN_FOREST_TRAINER_0    ; 5D
	const KT_VIRIDIAN_FOREST_TRAINER_1    ; 5E
	const KT_VIRIDIAN_FOREST_TRAINER_2    ; 5F
	const KT_PEWTER_GYM_LEADER            ; 60
	const KT_PEWTER_GYM_TRAINER_0         ; 61
	const KT_MT_MOON_1_TRAINER_0          ; 62
	const KT_MT_MOON_1_TRAINER_1          ; 63
	const KT_MT_MOON_1_TRAINER_2          ; 64
	const KT_MT_MOON_1_TRAINER_3          ; 65
	const KT_MT_MOON_1_TRAINER_4          ; 66
	const KT_MT_MOON_1_TRAINER_5          ; 67
	const KT_MT_MOON_1_TRAINER_6          ; 68
	const KT_MT_MOON_EXIT_SUPER_NERD      ; 69
	const KT_MT_MOON_3_TRAINER_0          ; 6A
	const KT_MT_MOON_3_TRAINER_1          ; 6B
	const KT_MT_MOON_3_TRAINER_2          ; 6C
	const KT_MT_MOON_3_TRAINER_3          ; 6D
	const KT_CERULEAN_GYM_LEADER          ; 6E
	const KT_CERULEAN_GYM_TRAINER_0       ; 6F
	const KT_CERULEAN_GYM_TRAINER_1       ; 70
	const KT_ROCK_TUNNEL_1_TRAINER_0      ; 71
	const KT_ROCK_TUNNEL_1_TRAINER_1      ; 72
	const KT_ROCK_TUNNEL_1_TRAINER_2      ; 73
	const KT_ROCK_TUNNEL_1_TRAINER_3      ; 74
	const KT_ROCK_TUNNEL_1_TRAINER_4      ; 75
	const KT_ROCK_TUNNEL_1_TRAINER_5      ; 76
	const KT_ROCK_TUNNEL_1_TRAINER_6      ; 77
	const KT_VERMILION_GYM_LEADER         ; 78
	const KT_VERMILION_GYM_TRAINER_0      ; 79
	const KT_VERMILION_GYM_TRAINER_1      ; 7A
	const KT_VERMILION_GYM_TRAINER_2      ; 7B
	const KT_SS_ANNE_5_TRAINER_0          ; 7C
	const KT_SS_ANNE_5_TRAINER_1          ; 7D
	const KT_SS_ANNE_8_TRAINER_0          ; 7E
	const KT_SS_ANNE_8_TRAINER_1          ; 7F
	const KT_SS_ANNE_8_TRAINER_2          ; 80
	const KT_SS_ANNE_8_TRAINER_3          ; 81
	const KT_SS_ANNE_9_TRAINER_0          ; 82
	const KT_SS_ANNE_9_TRAINER_1          ; 83
	const KT_SS_ANNE_9_TRAINER_2          ; 84
	const KT_SS_ANNE_9_TRAINER_3          ; 85
	const KT_SS_ANNE_10_TRAINER_0         ; 86
	const KT_SS_ANNE_10_TRAINER_1         ; 87
	const KT_SS_ANNE_10_TRAINER_2         ; 88
	const KT_SS_ANNE_10_TRAINER_3         ; 89
	const KT_SS_ANNE_10_TRAINER_4         ; 8A
	const KT_SS_ANNE_10_TRAINER_5         ; 8B
	const KT_CELADON_GYM_LEADER           ; 8C
	const KT_CELADON_GYM_TRAINER_0        ; 8D
	const KT_CELADON_GYM_TRAINER_1        ; 8E
	const KT_CELADON_GYM_TRAINER_2        ; 8F
	const KT_CELADON_GYM_TRAINER_3        ; 90
	const KT_CELADON_GYM_TRAINER_4        ; 91
	const KT_CELADON_GYM_TRAINER_5        ; 92
	const KT_CELADON_GYM_TRAINER_6        ; 93
	const KT_GAME_CORNER_ROCKET           ; 94
	const KT_POKEMONTOWER_3_TRAINER_0     ; 95
	const KT_POKEMONTOWER_3_TRAINER_1     ; 96
	const KT_POKEMONTOWER_3_TRAINER_2     ; 97
	const KT_POKEMONTOWER_4_TRAINER_0     ; 98
	const KT_POKEMONTOWER_4_TRAINER_1     ; 99
	const KT_POKEMONTOWER_4_TRAINER_2     ; 9A
	const KT_POKEMONTOWER_5_TRAINER_0     ; 9B
	const KT_POKEMONTOWER_5_TRAINER_1     ; 9C
	const KT_POKEMONTOWER_5_TRAINER_2     ; 9D
	const KT_POKEMONTOWER_5_TRAINER_3     ; 9E
	const KT_POKEMONTOWER_6_TRAINER_0     ; 9F
	const KT_POKEMONTOWER_6_TRAINER_1     ; A0
	const KT_POKEMONTOWER_6_TRAINER_2     ; A1
	const KT_POKEMONTOWER_7_TRAINER_0     ; A2
	const KT_POKEMONTOWER_7_TRAINER_1     ; A3
	const KT_POKEMONTOWER_7_TRAINER_2     ; A4
	const KT_KARATE_MASTER                ; A5
	const KT_FIGHTING_DOJO_TRAINER_0      ; A6
	const KT_FIGHTING_DOJO_TRAINER_1      ; A7
	const KT_FIGHTING_DOJO_TRAINER_2      ; A8
	const KT_FIGHTING_DOJO_TRAINER_3      ; A9
	const KT_SAFFRON_GYM_LEADER           ; AA
	const KT_SAFFRON_GYM_TRAINER_0        ; AB
	const KT_SAFFRON_GYM_TRAINER_1        ; AC
	const KT_SAFFRON_GYM_TRAINER_2        ; AD
	const KT_SAFFRON_GYM_TRAINER_3        ; AE
	const KT_SAFFRON_GYM_TRAINER_4        ; AF
	const KT_SAFFRON_GYM_TRAINER_5        ; B0
	const KT_SAFFRON_GYM_TRAINER_6        ; B1
	const KT_ROCKET_HIDEOUT_1_TRAINER_0   ; B2
	const KT_ROCKET_HIDEOUT_1_TRAINER_1   ; B3
	const KT_ROCKET_HIDEOUT_1_TRAINER_2   ; B4
	const KT_ROCKET_HIDEOUT_1_TRAINER_3   ; B5
	const KT_ROCKET_HIDEOUT_1_TRAINER_4   ; B6
	const KT_ROCKET_HIDEOUT_2_TRAINER_0   ; B7
	const KT_ROCKET_HIDEOUT_3_TRAINER_0   ; B8
	const KT_ROCKET_HIDEOUT_3_TRAINER_1   ; B9
	const KT_ROCKET_HIDEOUT_4_TRAINER_0   ; BA
	const KT_ROCKET_HIDEOUT_4_TRAINER_1   ; BB
	const KT_ROCKET_HIDEOUT_4_TRAINER_2   ; BC
	const KT_SILPH_CO_2F_TRAINER_0        ; BD
	const KT_SILPH_CO_2F_TRAINER_1        ; BE
	const KT_SILPH_CO_2F_TRAINER_2        ; BF
	const KT_SILPH_CO_2F_TRAINER_3        ; C0
	const KT_SILPH_CO_3F_TRAINER_0        ; C1
	const KT_SILPH_CO_3F_TRAINER_1        ; C2
	const KT_SILPH_CO_4F_TRAINER_0        ; C3
	const KT_SILPH_CO_4F_TRAINER_1        ; C4
	const KT_SILPH_CO_4F_TRAINER_2        ; C5
	const KT_SILPH_CO_5F_TRAINER_0        ; C6
	const KT_SILPH_CO_5F_TRAINER_1        ; C7
	const KT_SILPH_CO_5F_TRAINER_2        ; C8
	const KT_SILPH_CO_5F_TRAINER_3        ; C9
	const KT_SILPH_CO_6F_TRAINER_0        ; CA
	const KT_SILPH_CO_6F_TRAINER_1        ; CB
	const KT_SILPH_CO_6F_TRAINER_2        ; CC
	const KT_SILPH_CO_7F_TRAINER_0        ; CD
	const KT_SILPH_CO_7F_TRAINER_1        ; CE
	const KT_SILPH_CO_7F_TRAINER_2        ; CF
	const KT_SILPH_CO_7F_TRAINER_3        ; D0
	const KT_SILPH_CO_8F_TRAINER_0        ; D1
	const KT_SILPH_CO_8F_TRAINER_1        ; D2
	const KT_SILPH_CO_8F_TRAINER_2        ; D3
	const KT_ROCK_TUNNEL_2_TRAINER_0      ; D4
	const KT_ROCK_TUNNEL_2_TRAINER_1      ; D5
	const KT_ROCK_TUNNEL_2_TRAINER_2      ; D6
	const KT_ROCK_TUNNEL_2_TRAINER_3      ; D7
	const KT_ROCK_TUNNEL_2_TRAINER_4      ; D8
	const KT_ROCK_TUNNEL_2_TRAINER_5      ; D9
	const KT_ROCK_TUNNEL_2_TRAINER_6      ; DA
	const KT_ROCK_TUNNEL_2_TRAINER_7      ; DB
	const KT_SILPH_CO_9F_TRAINER_0        ; DC
	const KT_SILPH_CO_9F_TRAINER_1        ; DE
	const KT_SILPH_CO_9F_TRAINER_2        ; DF
	const KT_SILPH_CO_10F_TRAINER_0       ; E0
	const KT_SILPH_CO_10F_TRAINER_1       ; E1
	const KT_SILPH_CO_11F_TRAINER_0       ; E2
	const KT_SILPH_CO_11F_TRAINER_1       ; E3
