const_value = 0

	const KT_NOT_KILLABLE                 ; 00
	const KT_CERULEAN_CITY_ROCKET_THIEF   ; 01
	const KT_ROUTE_3_TRAINER_0            ; 02
	const KT_ROUTE_3_TRAINER_1            ; 03
	const KT_ROUTE_3_TRAINER_2            ; 04
	const KT_ROUTE_3_TRAINER_3            ; 05
	const KT_ROUTE_3_TRAINER_4            ; 06
	const KT_ROUTE_3_TRAINER_5            ; 07
	const KT_ROUTE_3_TRAINER_6            ; 08
	const KT_ROUTE_3_TRAINER_7            ; 09
	const KT_ROUTE_4_TRAINER_0            ; 0A
	const KT_ROUTE_6_TRAINER_0            ; 0B
	const KT_ROUTE_6_TRAINER_1            ; 0C
	const KT_ROUTE_6_TRAINER_2            ; 0D
	const KT_ROUTE_6_TRAINER_3            ; 0E
	const KT_ROUTE_6_TRAINER_4            ; 0F
	const KT_ROUTE_6_TRAINER_5            ; 10
	const KT_ROUTE_24_ROCKET              ; 11
	const KT_ROUTE_24_TRAINER_0           ; 12
	const KT_ROUTE_24_TRAINER_1           ; 13
	const KT_ROUTE_24_TRAINER_2           ; 14
	const KT_ROUTE_24_TRAINER_3           ; 15
	const KT_ROUTE_24_TRAINER_4           ; 16
	const KT_ROUTE_24_TRAINER_5           ; 17
	const KT_VIRIDIAN_FOREST_TRAINER_0    ; 18
	const KT_VIRIDIAN_FOREST_TRAINER_1    ; 19
	const KT_VIRIDIAN_FOREST_TRAINER_2    ; 1A
	const KT_PEWTER_GYM_LEADER            ; 1B
	const KT_PEWTER_GYM_TRAINER_0         ; 1C
	const KT_MT_MOON_1_TRAINER_0          ; 1D
	const KT_MT_MOON_1_TRAINER_1          ; 1E
	const KT_MT_MOON_1_TRAINER_2          ; 1F
	const KT_MT_MOON_1_TRAINER_3          ; 20
	const KT_MT_MOON_1_TRAINER_4          ; 21
	const KT_MT_MOON_1_TRAINER_5          ; 22
	const KT_MT_MOON_1_TRAINER_6          ; 23
	const KT_MT_MOON_EXIT_SUPER_NERD      ; 24
	const KT_MT_MOON_3_TRAINER_0          ; 25
	const KT_MT_MOON_3_TRAINER_1          ; 26
	const KT_MT_MOON_3_TRAINER_2          ; 27
	const KT_MT_MOON_3_TRAINER_3          ; 28
	const KT_CERULEAN_GYM_LEADER          ; 29
	const KT_CERULEAN_GYM_TRAINER_0       ; 2A
	const KT_CERULEAN_GYM_TRAINER_1       ; 2B
