const_value = 0

	const KT_NOT_KILLABLE                 ; 000
	const KT_CERULEAN_CITY_ROCKET_THIEF   ; 001
	const KT_ROUTE_3_TRAINER_0            ; 002
	const KT_ROUTE_3_TRAINER_1            ; 003
	const KT_ROUTE_3_TRAINER_2            ; 004
	const KT_ROUTE_3_TRAINER_3            ; 005
	const KT_ROUTE_3_TRAINER_4            ; 006
	const KT_ROUTE_3_TRAINER_5            ; 007
	const KT_ROUTE_3_TRAINER_6            ; 008
	const KT_ROUTE_3_TRAINER_7            ; 009
	const KT_ROUTE_4_TRAINER_0            ; 00A
	const KT_ROUTE_6_TRAINER_0            ; 00B
	const KT_ROUTE_6_TRAINER_1            ; 00C
	const KT_ROUTE_6_TRAINER_2            ; 00D
	const KT_ROUTE_6_TRAINER_3            ; 00E
	const KT_ROUTE_6_TRAINER_4            ; 00F
	const KT_ROUTE_6_TRAINER_5            ; 010
	const KT_ROUTE_8_TRAINER_0            ; 011
	const KT_ROUTE_8_TRAINER_1            ; 012
	const KT_ROUTE_8_TRAINER_2            ; 013
	const KT_ROUTE_8_TRAINER_3            ; 014
	const KT_ROUTE_8_TRAINER_4            ; 015
	const KT_ROUTE_8_TRAINER_5            ; 016
	const KT_ROUTE_8_TRAINER_6            ; 017
	const KT_ROUTE_8_TRAINER_7            ; 018
	const KT_ROUTE_8_TRAINER_8            ; 019
	const KT_ROUTE_9_TRAINER_0            ; 01A
	const KT_ROUTE_9_TRAINER_1            ; 01B
	const KT_ROUTE_9_TRAINER_2            ; 01C
	const KT_ROUTE_9_TRAINER_3            ; 01D
	const KT_ROUTE_9_TRAINER_4            ; 01E
	const KT_ROUTE_9_TRAINER_5            ; 01F
	const KT_ROUTE_9_TRAINER_6            ; 020
	const KT_ROUTE_9_TRAINER_7            ; 021
	const KT_ROUTE_9_TRAINER_8            ; 022
	const KT_ROUTE_10_TRAINER_0           ; 023
	const KT_ROUTE_10_TRAINER_1           ; 024
	const KT_ROUTE_10_TRAINER_2           ; 025
	const KT_ROUTE_10_TRAINER_3           ; 026
	const KT_ROUTE_10_TRAINER_4           ; 027
	const KT_ROUTE_10_TRAINER_5           ; 028
	const KT_ROUTE_11_TRAINER_0           ; 029
	const KT_ROUTE_11_TRAINER_1           ; 02A
	const KT_ROUTE_11_TRAINER_2           ; 02B
	const KT_ROUTE_11_TRAINER_3           ; 02C
	const KT_ROUTE_11_TRAINER_4           ; 02D
	const KT_ROUTE_11_TRAINER_5           ; 02E
	const KT_ROUTE_11_TRAINER_6           ; 02F
	const KT_ROUTE_11_TRAINER_7           ; 030
	const KT_ROUTE_11_TRAINER_8           ; 031
	const KT_ROUTE_11_TRAINER_9           ; 032
	const KT_ROUTE_12_TRAINER_0           ; 033
	const KT_ROUTE_12_TRAINER_1           ; 034
	const KT_ROUTE_12_TRAINER_2           ; 035
	const KT_ROUTE_12_TRAINER_3           ; 036
	const KT_ROUTE_12_TRAINER_4           ; 037
	const KT_ROUTE_12_TRAINER_5           ; 038
	const KT_ROUTE_12_TRAINER_6           ; 039
	const KT_ROUTE_13_TRAINER_0           ; 03A
	const KT_ROUTE_13_TRAINER_1           ; 03B
	const KT_ROUTE_13_TRAINER_2           ; 03C
	const KT_ROUTE_13_TRAINER_3           ; 03D
	const KT_ROUTE_13_TRAINER_4           ; 03E
	const KT_ROUTE_13_TRAINER_5           ; 03F
	const KT_ROUTE_13_TRAINER_6           ; 040
	const KT_ROUTE_13_TRAINER_7           ; 041
	const KT_ROUTE_13_TRAINER_8           ; 042
	const KT_ROUTE_13_TRAINER_9           ; 043
	const KT_ROUTE_14_TRAINER_0           ; 044
	const KT_ROUTE_14_TRAINER_1           ; 045
	const KT_ROUTE_14_TRAINER_2           ; 046
	const KT_ROUTE_14_TRAINER_3           ; 047
	const KT_ROUTE_14_TRAINER_4           ; 048
	const KT_ROUTE_14_TRAINER_5           ; 049
	const KT_ROUTE_14_TRAINER_6           ; 04A
	const KT_ROUTE_14_TRAINER_7           ; 04B
	const KT_ROUTE_14_TRAINER_8           ; 04C
	const KT_ROUTE_14_TRAINER_9           ; 04D
	const KT_ROUTE_15_TRAINER_0           ; 04E
	const KT_ROUTE_15_TRAINER_1           ; 04F
	const KT_ROUTE_15_TRAINER_2           ; 050
	const KT_ROUTE_15_TRAINER_3           ; 051
	const KT_ROUTE_15_TRAINER_4           ; 052
	const KT_ROUTE_15_TRAINER_5           ; 053
	const KT_ROUTE_15_TRAINER_6           ; 054
	const KT_ROUTE_15_TRAINER_7           ; 055
	const KT_ROUTE_15_TRAINER_8           ; 056
	const KT_ROUTE_15_TRAINER_9           ; 057
	const KT_ROUTE_16_TRAINER_0           ; 058
	const KT_ROUTE_16_TRAINER_1           ; 059
	const KT_ROUTE_16_TRAINER_2           ; 05A
	const KT_ROUTE_16_TRAINER_3           ; 05B
	const KT_ROUTE_16_TRAINER_4           ; 05C
	const KT_ROUTE_16_TRAINER_5           ; 05D
	const KT_ROUTE_17_TRAINER_0           ; 05E
	const KT_ROUTE_17_TRAINER_1           ; 05F
	const KT_ROUTE_17_TRAINER_2           ; 060
	const KT_ROUTE_17_TRAINER_3           ; 061
	const KT_ROUTE_17_TRAINER_4           ; 062
	const KT_ROUTE_17_TRAINER_5           ; 063
	const KT_ROUTE_17_TRAINER_6           ; 064
	const KT_ROUTE_17_TRAINER_7           ; 065
	const KT_ROUTE_17_TRAINER_8           ; 066
	const KT_ROUTE_17_TRAINER_9           ; 067
	const KT_ROUTE_18_TRAINER_0           ; 068
	const KT_ROUTE_18_TRAINER_1           ; 069
	const KT_ROUTE_18_TRAINER_2           ; 06A
	const KT_ROUTE_19_TRAINER_0           ; 06B
	const KT_ROUTE_19_TRAINER_1           ; 06C
	const KT_ROUTE_19_TRAINER_2           ; 06D
	const KT_ROUTE_19_TRAINER_3           ; 06E
	const KT_ROUTE_19_TRAINER_4           ; 06F
	const KT_ROUTE_19_TRAINER_5           ; 070
	const KT_ROUTE_19_TRAINER_6           ; 071
	const KT_ROUTE_19_TRAINER_7           ; 072
	const KT_ROUTE_19_TRAINER_8           ; 073
	const KT_ROUTE_19_TRAINER_9           ; 074
	const KT_ROUTE_20_TRAINER_0           ; 075
	const KT_ROUTE_20_TRAINER_1           ; 076
	const KT_ROUTE_20_TRAINER_2           ; 077
	const KT_ROUTE_20_TRAINER_3           ; 078
	const KT_ROUTE_20_TRAINER_4           ; 079
	const KT_ROUTE_20_TRAINER_5           ; 07A
	const KT_ROUTE_20_TRAINER_6           ; 07B
	const KT_ROUTE_20_TRAINER_7           ; 07C
	const KT_ROUTE_20_TRAINER_8           ; 07D
	const KT_ROUTE_20_TRAINER_9           ; 07E
	const KT_ROUTE_21_TRAINER_0           ; 07F
	const KT_ROUTE_21_TRAINER_1           ; 080
	const KT_ROUTE_21_TRAINER_2           ; 081
	const KT_ROUTE_21_TRAINER_3           ; 082
	const KT_ROUTE_21_TRAINER_4           ; 083
	const KT_ROUTE_21_TRAINER_5           ; 084
	const KT_ROUTE_21_TRAINER_6           ; 085
	const KT_ROUTE_21_TRAINER_7           ; 086
	const KT_ROUTE_21_TRAINER_8           ; 087
	const KT_ROUTE_24_ROCKET              ; 088
	const KT_ROUTE_24_TRAINER_0           ; 089
	const KT_ROUTE_24_TRAINER_1           ; 08A
	const KT_ROUTE_24_TRAINER_2           ; 08B
	const KT_ROUTE_24_TRAINER_3           ; 08C
	const KT_ROUTE_24_TRAINER_4           ; 08D
	const KT_ROUTE_24_TRAINER_5           ; 08E
	const KT_ROUTE_25_TRAINER_0           ; 08F
	const KT_ROUTE_25_TRAINER_1           ; 090
	const KT_ROUTE_25_TRAINER_2           ; 091
	const KT_ROUTE_25_TRAINER_3           ; 092
	const KT_ROUTE_25_TRAINER_4           ; 093
	const KT_ROUTE_25_TRAINER_5           ; 094
	const KT_ROUTE_25_TRAINER_6           ; 095
	const KT_ROUTE_25_TRAINER_7           ; 096
	const KT_ROUTE_25_TRAINER_8           ; 097
	const KT_VIRIDIAN_GYM_LEADER          ; 098
	const KT_VIRIDIAN_GYM_TRAINER_0       ; 099
	const KT_VIRIDIAN_GYM_TRAINER_1       ; 09A
	const KT_VIRIDIAN_GYM_TRAINER_2       ; 09B
	const KT_VIRIDIAN_GYM_TRAINER_3       ; 09C
	const KT_VIRIDIAN_GYM_TRAINER_4       ; 09D
	const KT_VIRIDIAN_GYM_TRAINER_5       ; 09E
	const KT_VIRIDIAN_GYM_TRAINER_6       ; 09F
	const KT_VIRIDIAN_GYM_TRAINER_7       ; 0A0
	const KT_VIRIDIAN_FOREST_TRAINER_0    ; 0A1
	const KT_VIRIDIAN_FOREST_TRAINER_1    ; 0A2
	const KT_VIRIDIAN_FOREST_TRAINER_2    ; 0A3
	const KT_PEWTER_GYM_LEADER            ; 0A4
	const KT_PEWTER_GYM_TRAINER_0         ; 0A5
	const KT_MT_MOON_1_TRAINER_0          ; 0A6
	const KT_MT_MOON_1_TRAINER_1          ; 0A7
	const KT_MT_MOON_1_TRAINER_2          ; 0A8
	const KT_MT_MOON_1_TRAINER_3          ; 0A9
	const KT_MT_MOON_1_TRAINER_4          ; 0AA
	const KT_MT_MOON_1_TRAINER_5          ; 0AB
	const KT_MT_MOON_1_TRAINER_6          ; 0AC
	const KT_MT_MOON_EXIT_SUPER_NERD      ; 0AD
	const KT_MT_MOON_3_TRAINER_0          ; 0AE
	const KT_MT_MOON_3_TRAINER_1          ; 0AF
	const KT_MT_MOON_3_TRAINER_2          ; 0B0
	const KT_MT_MOON_3_TRAINER_3          ; 0B1
	const KT_CERULEAN_GYM_LEADER          ; 0B2
	const KT_CERULEAN_GYM_TRAINER_0       ; 0B3
	const KT_CERULEAN_GYM_TRAINER_1       ; 0B4
	const KT_ROCK_TUNNEL_1_TRAINER_0      ; 0B5
	const KT_ROCK_TUNNEL_1_TRAINER_1      ; 0B6
	const KT_ROCK_TUNNEL_1_TRAINER_2      ; 0B7
	const KT_ROCK_TUNNEL_1_TRAINER_3      ; 0B8
	const KT_ROCK_TUNNEL_1_TRAINER_4      ; 0B9
	const KT_ROCK_TUNNEL_1_TRAINER_5      ; 0BA
	const KT_ROCK_TUNNEL_1_TRAINER_6      ; 0BB
	const KT_VERMILION_GYM_LEADER         ; 0BC
	const KT_VERMILION_GYM_TRAINER_0      ; 0BD
	const KT_VERMILION_GYM_TRAINER_1      ; 0BE
	const KT_VERMILION_GYM_TRAINER_2      ; 0BF
	const KT_SS_ANNE_5_TRAINER_0          ; 0C0
	const KT_SS_ANNE_5_TRAINER_1          ; 0C1
	const KT_SS_ANNE_8_TRAINER_0          ; 0C2
	const KT_SS_ANNE_8_TRAINER_1          ; 0C3
	const KT_SS_ANNE_8_TRAINER_2          ; 0C4
	const KT_SS_ANNE_8_TRAINER_3          ; 0C5
	const KT_SS_ANNE_9_TRAINER_0          ; 0C6
	const KT_SS_ANNE_9_TRAINER_1          ; 0C7
	const KT_SS_ANNE_9_TRAINER_2          ; 0C8
	const KT_SS_ANNE_9_TRAINER_3          ; 0C9
	const KT_SS_ANNE_10_TRAINER_0         ; 0CA
	const KT_SS_ANNE_10_TRAINER_1         ; 0CB
	const KT_SS_ANNE_10_TRAINER_2         ; 0CC
	const KT_SS_ANNE_10_TRAINER_3         ; 0CD
	const KT_SS_ANNE_10_TRAINER_4         ; 0CE
	const KT_SS_ANNE_10_TRAINER_5         ; 0CF
	const KT_CELADON_GYM_LEADER           ; 0D0
	const KT_CELADON_GYM_TRAINER_0        ; 0D1
	const KT_CELADON_GYM_TRAINER_1        ; 0D2
	const KT_CELADON_GYM_TRAINER_2        ; 0D3
	const KT_CELADON_GYM_TRAINER_3        ; 0D4
	const KT_CELADON_GYM_TRAINER_4        ; 0D5
	const KT_CELADON_GYM_TRAINER_5        ; 0D6
	const KT_CELADON_GYM_TRAINER_6        ; 0D7
	const KT_GAME_CORNER_ROCKET           ; 0D8
	const KT_POKEMONTOWER_3_TRAINER_0     ; 0D9
	const KT_POKEMONTOWER_3_TRAINER_1     ; 0DA
	const KT_POKEMONTOWER_3_TRAINER_2     ; 0DB
	const KT_POKEMONTOWER_4_TRAINER_0     ; 0DC
	const KT_POKEMONTOWER_4_TRAINER_1     ; 0DD
	const KT_POKEMONTOWER_4_TRAINER_2     ; 0DE
	const KT_POKEMONTOWER_5_TRAINER_0     ; 0DF
	const KT_POKEMONTOWER_5_TRAINER_1     ; 0E0
	const KT_POKEMONTOWER_5_TRAINER_2     ; 0E1
	const KT_POKEMONTOWER_5_TRAINER_3     ; 0E2
	const KT_POKEMONTOWER_6_TRAINER_0     ; 0E3
	const KT_POKEMONTOWER_6_TRAINER_1     ; 0E4
	const KT_POKEMONTOWER_6_TRAINER_2     ; 0E5
	const KT_POKEMONTOWER_7_TRAINER_0     ; 0E6
	const KT_POKEMONTOWER_7_TRAINER_1     ; 0E7
	const KT_POKEMONTOWER_7_TRAINER_2     ; 0E8
	const KT_FUCHSIA_GYM_LEADER           ; 0E9
	const KT_FUCHSIA_GYM_TRAINER_0        ; 0EA
	const KT_FUCHSIA_GYM_TRAINER_1        ; 0EB
	const KT_FUCHSIA_GYM_TRAINER_2        ; 0EC
	const KT_FUCHSIA_GYM_TRAINER_3        ; 0ED
	const KT_FUCHSIA_GYM_TRAINER_4        ; 0EE
	const KT_FUCHSIA_GYM_TRAINER_5        ; 0EF
	const KT_MANSION_1_TRAINER_0          ; 0F0
	const KT_CINNABAR_GYM_LEADER          ; 0F1
	const KT_CINNABAR_GYM_TRAINER_0       ; 0F2
	const KT_CINNABAR_GYM_TRAINER_1       ; 0F3
	const KT_CINNABAR_GYM_TRAINER_2       ; 0F4
	const KT_CINNABAR_GYM_TRAINER_3       ; 0F5
	const KT_CINNABAR_GYM_TRAINER_4       ; 0F6
	const KT_CINNABAR_GYM_TRAINER_5       ; 0F7
	const KT_CINNABAR_GYM_TRAINER_6       ; 0F8
	const KT_KARATE_MASTER                ; 0F9
	const KT_FIGHTING_DOJO_TRAINER_0      ; 0FA
	const KT_FIGHTING_DOJO_TRAINER_1      ; 0FB
	const KT_FIGHTING_DOJO_TRAINER_2      ; 0FC
	const KT_FIGHTING_DOJO_TRAINER_3      ; 0FD
	const KT_SAFFRON_GYM_LEADER           ; 0FE
	const KT_SAFFRON_GYM_TRAINER_0        ; 0FF
	const KT_SAFFRON_GYM_TRAINER_1        ; 100
	const KT_SAFFRON_GYM_TRAINER_2        ; 101
	const KT_SAFFRON_GYM_TRAINER_3        ; 102
	const KT_SAFFRON_GYM_TRAINER_4        ; 103
	const KT_SAFFRON_GYM_TRAINER_5        ; 104
	const KT_SAFFRON_GYM_TRAINER_6        ; 105
	const KT_ROCKET_HIDEOUT_1_TRAINER_0   ; 106
	const KT_ROCKET_HIDEOUT_1_TRAINER_1   ; 107
	const KT_ROCKET_HIDEOUT_1_TRAINER_2   ; 108
	const KT_ROCKET_HIDEOUT_1_TRAINER_3   ; 109
	const KT_ROCKET_HIDEOUT_1_TRAINER_4   ; 10A
	const KT_ROCKET_HIDEOUT_2_TRAINER_0   ; 10B
	const KT_ROCKET_HIDEOUT_3_TRAINER_0   ; 10C
	const KT_ROCKET_HIDEOUT_3_TRAINER_1   ; 10D
	const KT_ROCKET_HIDEOUT_4_TRAINER_0   ; 10E
	const KT_ROCKET_HIDEOUT_4_TRAINER_1   ; 10F
	const KT_ROCKET_HIDEOUT_4_TRAINER_2   ; 110
	const KT_SILPH_CO_2F_TRAINER_0        ; 111
	const KT_SILPH_CO_2F_TRAINER_1        ; 112
	const KT_SILPH_CO_2F_TRAINER_2        ; 113
	const KT_SILPH_CO_2F_TRAINER_3        ; 114
	const KT_SILPH_CO_3F_TRAINER_0        ; 115
	const KT_SILPH_CO_3F_TRAINER_1        ; 116
	const KT_SILPH_CO_4F_TRAINER_0        ; 117
	const KT_SILPH_CO_4F_TRAINER_1        ; 118
	const KT_SILPH_CO_4F_TRAINER_2        ; 119
	const KT_SILPH_CO_5F_TRAINER_0        ; 11A
	const KT_SILPH_CO_5F_TRAINER_1        ; 11B
	const KT_SILPH_CO_5F_TRAINER_2        ; 11C
	const KT_SILPH_CO_5F_TRAINER_3        ; 11D
	const KT_SILPH_CO_6F_TRAINER_0        ; 11E
	const KT_SILPH_CO_6F_TRAINER_1        ; 11F
	const KT_SILPH_CO_6F_TRAINER_2        ; 120
	const KT_SILPH_CO_7F_TRAINER_0        ; 121
	const KT_SILPH_CO_7F_TRAINER_1        ; 122
	const KT_SILPH_CO_7F_TRAINER_2        ; 123
	const KT_SILPH_CO_7F_TRAINER_3        ; 124
	const KT_SILPH_CO_8F_TRAINER_0        ; 125
	const KT_SILPH_CO_8F_TRAINER_1        ; 126
	const KT_SILPH_CO_8F_TRAINER_2        ; 127
	const KT_MANSION_2_TRAINER_0          ; 128
	const KT_MANSION_3_TRAINER_0          ; 129
	const KT_MANSION_3_TRAINER_1          ; 12A
	const KT_MANSION_4_TRAINER_0          ; 12B
	const KT_MANSION_4_TRAINER_1          ; 12C
	const KT_ROCK_TUNNEL_2_TRAINER_0      ; 12D
	const KT_ROCK_TUNNEL_2_TRAINER_1      ; 12E
	const KT_ROCK_TUNNEL_2_TRAINER_2      ; 12F
	const KT_ROCK_TUNNEL_2_TRAINER_3      ; 130
	const KT_ROCK_TUNNEL_2_TRAINER_4      ; 131
	const KT_ROCK_TUNNEL_2_TRAINER_5      ; 132
	const KT_ROCK_TUNNEL_2_TRAINER_6      ; 133
	const KT_ROCK_TUNNEL_2_TRAINER_7      ; 134
	const KT_SILPH_CO_9F_TRAINER_0        ; 135
	const KT_SILPH_CO_9F_TRAINER_1        ; 136
	const KT_SILPH_CO_9F_TRAINER_2        ; 137
	const KT_SILPH_CO_10F_TRAINER_0       ; 138
	const KT_SILPH_CO_10F_TRAINER_1       ; 139
	const KT_SILPH_CO_11F_TRAINER_0       ; 13A
	const KT_SILPH_CO_11F_TRAINER_1       ; 13B
